### PR TITLE
Task 4 rds cloud database

### PR DESCRIPTION
**Pull request by LittleCryingGirl**
FE: https://d2ydqlmfrv066n.cloudfront.net

DONE 1 - Task 4.1 is implemented
DONE 3 - TASK 4.2 is implemented lambda links are provided and returns data
DONE 4 - TASK 4.3 is implemented lambda links are provided and products is stored in DB (call TASK 4.2 to see the product)
DONE 5 - Your own Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend. Link to a working Front-End application is provided for cross-check reviewer.
https://github.com/LittleCryingGirl/nodejs-aws-fe/pull/4/files

Additional (optional) tasks (but nice to have):

+1 - POST/products lambda functions returns error 400 status code if product data is invalid
DONE +1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
DONE +1 - All lambdas do console.log for each incoming requests and their arguments
+1 - Transaction based creation of product (in case stock creation is failed then related to this stock product is not created and not ready to be used by the end user and vice versa) (https://devcenter.kinvey.com/nodejs/tutorials/bl-transactional-support)

### CODE REVIEW

**Comment by olenastarchak** [comment]
Hi, can you please provide lambda links for testing?
I tried to use FE application, but you didn't link creation of product.
Also I tried endpoints from your previous PR:
- https://onb1b5p13m.execute-api.eu-west-1.amazonaws.com/dev/products - returns products, but last one seems to have wrong values (  {"id":null,"description":"We decided to commemorate Kii Pohaku in the way we do best—by incorporating them into our newest laser-cut rosette design on a quality laminate soprano ukulele.","price":99,"title":"Flight DUS371 Mahogany Soprano Ukulele","image_url":"https://flightmusic.com/wp-content/uploads/2018/05/DUS445-IMG-02-1.jpg","product_id":null,"count":null}]}  )
- https://onb1b5p13m.execute-api.eu-west-1.amazonaws.com/dev/products/b9504349-ed28-4a48-b58c-48b4fbc9d3cf - getProductById returns 500 error

**Comment by maximsan** [comment]
image
Hello! It seems product creation does not work from FE .
I also was not able to post a product from postman
image
As @olenastarchak mentioned, I have the same problems with your lambdas.
Please check and let me know if you fix it or not.

**Comment by LittleCryingGirl** [comment]
Hi guys! Thank you for you patient!
I deploy correct app and now its working
@maximsan @olenastarchak

**Comment by maximsan** [comment]
Hello, @LittleCryingGirl ! I rechecked and It still does not work. Or maybe I fetched data from wrong API. Could you attach link to your working lambda ?  I still can't add product on FE application.

**Comment by olenastarchak** [comment]
hey, can't get product by id because all of the products in table have id null

**Comment by LittleCryingGirl** [comment]
hey again, I updated app and now things must works 
thank you again @olenastarchak @maximsan

**Pull request merged**
